{% set name = "snaphu" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f1f35fe58d89182ee965a10089f22f99d5a56a825e356b66745ccaa065be9b5d

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: true  # [py<39 or not unix]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - cmake >=3.15
    - make
  host:
    - python
    - pip
    - scikit-build-core >=0.4
    - setuptools_scm
  run:
    - python
    - numpy >=1.20

test:
  imports:
    - snaphu
  requires:
    - pip
    - pytest >=6
    - pytest-cov >=3
  source_files:
    - test
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/isce-framework/snaphu-py
  summary: A simple Python wrapper for SNAPHU
  license: (Apache-2.0 OR BSD-3-Clause) AND LicenseRef-SNAPHU
  license_file:
    - LICENSE-Apache-2.0
    - LICENSE-BSD-3-Clause
    - ext/snaphu/README

extra:
  recipe-maintainers:
    - gmgunter
